files:
  operationConfig.mustache:
    destinationFilename: {{src}}/api/operation_config/OperationConfig.java
    templateType: SupportingFiles
  operations.mustache:
    destinationFilename: {{src}}/api/operation_config/Operations.java
    templateType: SupportingFiles
  operationLookup.mustache:
    destinationFilename: {{src}}/api/operation_config/OperationLookup.java
    templateType: SupportingFiles
  handlers.mustache:
    destinationFilename: {{src}}/api/handlers/__handlers.java
    templateType: SupportingFiles
  interceptors.mustache:
    destinationFilename: {{src}}/api/interceptors/__interceptors.java
    templateType: SupportingFiles
