---
nav:
  - 'Developer Guides': index.md
  - 'aws-arch': aws-arch
  - 'cdk-graph': cdk-graph
  - 'cdk-graph-plugin-diagram': cdk-graph-plugin-diagram
  - 'cloudscape-react-ts-website': cloudscape-react-ts-website
  - 'identity': identity
  - 'nx-monorepo': nx-monorepo
  - 'pdk-nag': pdk-nag
  - 'pipeline': pipeline
  - 'static-website': static-website
  - 'type-safe-api': type-safe-api