name: "PDK Init"
description: "Initialize the PDK monorepo by installing engines, dependencies, and synthesizing project."
runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    # https://github.com/pnpm/action-setup
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 8
        run_install: false
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install npm
      shell: bash
      run: npm install -g npm@8.19.4
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
    - name: Synth Project
      shell: bash
      run: pnpm projen
      env:
        HUSKY: "0" # By default do not run HUSKY install
