files:
  modelGenericInterfaces.mustache:
    destinationFilename: .ts
    templateType: Model
  modelEnum.mustache:
    destinationFilename: .ts
    templateType: Model
  operationConfig.mustache:
    destinationFilename: /OperationConfig.ts
    templateType: API
