files:
  operationConfig.mustache:
    destinationFilename: {{src}}/api/operation_config/OperationConfig.java
    templateType: SupportingFiles
  operations.mustache:
    destinationFilename: {{src}}/api/operation_config/Operations.java
    templateType: SupportingFiles
  handlers.mustache:
    destinationFilename: {{src}}/__handlers.java
    templateType: SupportingFiles
  interceptors.mustache:
    destinationFilename: {{src}}/__interceptors.java
    templateType: SupportingFiles
