---
nav:
  - index.md
  - "Synthesis": synthesis.md
  - "Building your projects": building.md
  - "Dependencies": dependencies.md
  - "Caching": caching.md
  - "Dependency Visualization": dependency_visualization.md
  - "Escape hatches": escape_hatches.md
  - "Troubleshooting": troubleshooting.md
