files:
  operationConfig.mustache:
    destinationFilename: {{src}}/apis/tags/default_api_operation_config.py
    templateType: SupportingFiles
  response.mustache:
    destinationFilename: {{src}}/response.py
    templateType: SupportingFiles
  interceptors.mustache:
    destinationFilename: {{src}}/__interceptors.py
    templateType: SupportingFiles
