files:
  operationConfig.mustache:
    destinationFilename: /OperationConfig.java
    templateType: API
  operations.mustache:
    destinationFilename: /Operations.java
    templateType: API
  operationLookup.mustache:
    destinationFilename: /OperationLookup.java
    templateType: API
  handlers.mustache:
    destinationFilename: /Handlers.java
    templateType: API