files:
  operationConfig.mustache:
    destinationFilename: /OperationConfig.java
    templateType: API
  operationLookup.mustache:
    destinationFilename: /OperationLookup.java
    templateType: API
