files:
  operationConfig.mustache:
    destinationFilename: {{src}}/api/DefaultApi/OperationConfig.java
    templateType: SupportingFiles
  operations.mustache:
    destinationFilename: {{src}}/api/DefaultApi/Operations.java
    templateType: SupportingFiles
  operationLookup.mustache:
    destinationFilename: {{src}}/api/DefaultApi/OperationLookup.java
    templateType: SupportingFiles
  handlers.mustache:
    destinationFilename: {{src}}/api/DefaultApi/Handlers.java
    templateType: SupportingFiles