files:
  handlers.handlebars:
    destinationFilename: {{src}}/__all_handlers.ts
    templateType: SupportingFiles
  tests.handlebars:
    destinationFilename: {{tst}}/__all_tests.ts
    templateType: SupportingFiles
