files:
  modelGenericInterfaces.mustache:
    destinationFilename: .ts
    templateType: Model
  modelEnum.mustache:
    destinationFilename: .ts
    templateType: Model
  operationConfig.mustache:
    destinationFilename: {{src}}/apis/DefaultApi/OperationConfig.ts
    templateType: SupportingFiles
  index.mustache:
    destinationFilename: {{src}}/index.ts
    templateType: SupportingFiles
  response.mustache:
    destinationFilename: {{src}}/response/response.ts
    templateType: SupportingFiles
  interceptors.mustache:
    destinationFilename: {{src}}/__interceptors.ts
    templateType: SupportingFiles
