site_name: AWS Prototyping SDK (PDK)
site_description: AWS Prototyping SDK (PDK)
repo_name: aws/aws-prototyping-sdk
repo_url: https://github.com/aws/aws-prototyping-sdk
site_url: https://github.com/aws/aws-prototyping-sdk
copyright: Copyright &copy; 2022 Amazon Web Services, Inc.
use_directory_urls: false
docs_dir: content
extra_css:
  - assets/stylesheets/extra.css

nav:
  - ...

extra:
  social:
    - icon: fontawesome/brands/aws
      name: Amazon Web Services, Inc.
      link: https://aws.amazon.com

theme:
  name: material
  font: false
  logo: assets/images/logo.png
  icon:
    logo: fontawesome/brands/aws
    repo: fontawesome/brands/github
  favicon: assets/images/favicon.png
  palette:
    scheme: default
  features:
    - toc.follow
    - navigation.indexes
    - navigation.instant
    - navigation.tabs

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      repo_url_shortener: true
      provider: github
      user: aws
      repo: pdk
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      toc_depth: 3
plugins:
  - awesome-pages:
      filename: .pages.yml
  - git-revision-date
  - search
  - redirects:
      redirect_maps:
        "index.md": "welcome/index.md"
