---
nav:
  - index.md
  - "Migration guide": "migration_guide.md"
  - "Learning Series":
    - "1. Your first AWS PDK project": your_first_aws_pdk_project.md
    - "2. Shopping List application": "shopping_list_app.md"
