files:
  handlers.handlebars:
    destinationFilename: {{src}}/__all_handlers.java
    templateType: SupportingFiles
  tests.handlebars:
    destinationFilename: {{tst}}/__all_tests.java
    templateType: SupportingFiles
