---
nav:
  - index.md
  - "REST APIs":
    - "Getting Started": getting_started.md
    - "Using Smithy": using_smithy.md
    - "Using OpenAPI": using_openapi.md
    - "Lambda Handlers": lambda_handlers.md
    - "Interceptors": interceptors.md
    - "Integrations": integrations.md
    - "Mocking Responses": mocking_responses.md
    - "Authorizers": authorizers.md
    - "API Keys": api_keys.md
    - "React Hooks": typescript_react_query_hooks.md
    - "Custom Integration: ECS & NLB": custom_integration_ecs.md
  - "WebSocket APIs":
    - "Getting Started": websocket_getting_started.md
    - "Using Smithy": websocket_using_smithy.md
    - "Using OpenAPI": websocket_using_openapi.md
    - "Lambda Handlers": websocket_lambda_handlers.md
    - "Server SDKs": websocket_server_sdk.md
    - "Clients": websocket_clients.md
    - "Interceptors": websocket_interceptors.md
    - "Integrations": websocket_integrations.md
    - "Authorizers": websocket_authorizers.md
    - "React Hooks": websocket_typescript_react_hooks.md
  - "Troubleshooting": troubleshooting.md
