---
nav:
  - index.md
  - "Using Smithy": using_smithy.md
  - "Using OpenAPI": using_openapi.md
  - "Lambda Handlers": lambda_handlers.md
  - "Interceptors": interceptors.md
  - "Integrations": integrations.md
  - "Mocking Responses": mocking_responses.md
  - "Authorizers": authorizers.md
  - "API Keys": api_keys.md
  - "React Query Hooks": typescript_react_query_hooks.md
  - "Custom Integration: ECS & NLB": custom_integration_ecs.md
  - "Troubleshooting": troubleshooting.md
