---
nav:
  - index.md
  - "Using Smithy": using_smithy.md
  - "Using OpenAPI": using_openapi.md
  - "Integrations": integrations.md
  - "Authorizers": authorizers.md
  - "Lambda Handlers": lambda_handlers.md
  - "React Query Hooks": typescript_react_query_hooks.md
  - "API Keys": api_keys.md
