files:
  api.handlebars:
    destinationFilename: {{src}}/api.py
    templateType: SupportingFiles
  init.handlebars:
    destinationFilename: {{src}}/__init__.py
    templateType: SupportingFiles
  mockIntegrations.handlebars:
    destinationFilename: {{src}}/mock_integrations.py
    templateType: SupportingFiles
