files:
  api.mustache:
    destinationFilename: {{src}}/api.py
    templateType: SupportingFiles
  init.mustache:
    destinationFilename: {{src}}/__init__.py
    templateType: SupportingFiles
  mockIntegrations.mustache:
    destinationFilename: {{src}}/mock_integrations.py
    templateType: SupportingFiles
