files:
  modelGenericInterfaces.mustache:
    destinationFilename: .ts
    templateType: Model
  modelEnum.mustache:
    destinationFilename: .ts
    templateType: Model
  clientProvider.mustache:
    destinationFilename: ClientProvider.tsx
    templateType: API  
  hooks.handlebars:
    destinationFilename: Hooks.ts
    templateType: API
  index.mustache:
    destinationFilename: {{src}}/index.ts
    templateType: SupportingFiles
  apis.index.mustache:
    destinationFilename: {{src}}/apis/index.ts
    templateType: SupportingFiles
  README.md.mustache:
    destinationFilename: README.md
    templateType: SupportingFiles
