/*********************************************************************************************************************
 Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License").
 You may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 ******************************************************************************************************************** */
import { readFileSync, writeFileSync } from "fs";
import { NagMessageLevel } from "cdk-nag";
import { PackName, RuleMetadata } from "../src/packs/aws-prototyping-rules";

export class CreateRulesMarkdown {
  constructor() {}

  build() {
    const pack_prefix = PackName + "-";

    var markdown =
      "<!-- Generated by generate-pack-markdown.ts, do not edit directly. -->\n\n";

    markdown += readFileSync(
      "./scripts/pack-markdown-introduction.md"
    ).toString();

    markdown += "\n\n## Errors\n";

    const RuleMetadataErrors = RuleMetadata.filter(
      (obj) => obj.level === NagMessageLevel.ERROR
    );
    RuleMetadataErrors.sort((a, b) => (a.rule.name > b.rule.name ? 1 : -1));

    markdown += "\nTotal: `" + RuleMetadataErrors.length + "`\n\n";

    markdown += "| Rule ID | Cause | Explanation |\n";
    markdown +=
      "| ------------------ | ------------------ | ------------------ |\n";

    RuleMetadataErrors.forEach((rule) => {
      markdown +=
        "| " +
        pack_prefix +
        rule.rule.name +
        " | " +
        rule.info.replace("\n\n", "<br /><br />") +
        " | " +
        rule.explanation.replace("\n\n", "<br /><br />") +
        " |\n";
    });

    markdown += "\n\n";

    markdown += "## Warnings\n";

    const RuleMetadataWarnings = RuleMetadata.filter(
      (obj) => obj.level === NagMessageLevel.WARN
    );
    RuleMetadataWarnings.sort((a, b) => (a.rule.name > b.rule.name ? 1 : -1));

    markdown += "\nTotal: `" + RuleMetadataWarnings.length + "`\n\n";

    markdown += "| Rule ID | Cause | Explanation |\n";
    markdown +=
      "| ------------------ | ------------------ | ------------------ |\n";

    RuleMetadataWarnings.forEach((rule) => {
      markdown +=
        "| " +
        pack_prefix +
        rule.rule.name +
        " | " +
        rule.info.replace("\n\n", "<br /><br />") +
        " | " +
        rule.explanation.replace("\n\n", "<br /><br />") +
        " |\n";
    });

    writeFileSync("RULES.md", markdown);
    return;
  }
}

new CreateRulesMarkdown().build();
