files:
  handlers.handlebars:
    destinationFilename: {{src}}/__all_handlers.py
    templateType: SupportingFiles
  tests.handlebars:
    destinationFilename: {{tst}}/__all_tests.py
    templateType: SupportingFiles