files:
  api.mustache:
    destinationFilename: {{src}}/Api.java
    templateType: SupportingFiles
  apiProps.mustache:
    destinationFilename: {{src}}/ApiProps.java
    templateType: SupportingFiles
