files:
  api.mustache:
    destinationFilename: {{src}}/Api.java
    templateType: SupportingFiles
  apiProps.mustache:
    destinationFilename: {{src}}/ApiProps.java
    templateType: SupportingFiles
  mockIntegrations.mustache:
    destinationFilename: {{src}}/MockIntegrations.java
    templateType: SupportingFiles
