// ~~ Generated by projen. To modify, edit .projenrc.js and run "pnpm exec projen".
import type { aws_apigatewayv2 } from 'aws-cdk-lib';

/**
 * WebSocketStageProps
 */
export interface WebSocketStageProps {
  /**
   * The name of the stage.
   * @stability stable
   */
  readonly stageName?: string;
  /**
   * Throttle settings for the routes of this stage.
   * @default - no throttling configuration
   * @stability stable
   */
  readonly throttle?: aws_apigatewayv2.ThrottleSettings;
  /**
   * Stage variables for the stage. These are key-value pairs that you can define and use in your API routes.
   * The allowed characters for variable names and the required pattern for variable values are specified here: https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-apigateway-stage.html#cfn-apigateway-stage-variables
   * @default - No stage variables
   * @stability stable
   */
  readonly stageVariables?: Record<string, string>;
  /**
   * The options for custom domain and api mapping.
   * @default - no custom domain and api mapping configuration
   * @stability stable
   */
  readonly domainMapping?: aws_apigatewayv2.DomainMappingOptions;
  /**
   * Specifies whether detailed metrics are enabled.
   * @default false
   * @stability stable
   */
  readonly detailedMetricsEnabled?: boolean;
  /**
   * The description for the API stage.
   * @default - no description
   * @stability stable
   */
  readonly description?: string;
  /**
   * Whether updates to an API automatically trigger a new deployment.
   * @default false
   * @stability stable
   */
  readonly autoDeploy?: boolean;
  /**
   * Settings for access logging.
   * @default - No access logging
   * @stability stable
   */
  readonly accessLogSettings?: aws_apigatewayv2.IAccessLogSettings;
}
