files:
  api.mustache:
    destinationFilename: {{src}}/api.ts
    templateType: SupportingFiles
  index.mustache:
    destinationFilename: {{src}}/index.ts
    templateType: SupportingFiles
  mockIntegrations.mustache:
    destinationFilename: {{src}}/mock-integrations.ts
    templateType: SupportingFiles
