files:
  modelGenericInterfaces.mustache:
    destinationFilename: .ts
    templateType: Model
  modelEnum.mustache:
    destinationFilename: .ts
    templateType: Model
  client.mustache:
    destinationFilename: {{src}}/client/client.ts
    templateType: SupportingFiles
  index.mustache:
    destinationFilename: {{src}}/index.ts
    templateType: SupportingFiles
