files:
  modelGenericInterfaces.mustache:
    destinationFilename: .ts
    templateType: Model
  modelEnum.mustache:
    destinationFilename: .ts
    templateType: Model
  operationConfig.mustache:
    destinationFilename: {{src}}/server/operation-config.ts
    templateType: SupportingFiles
  serverSdk.mustache:
    destinationFilename: {{src}}/server/server-sdk.ts
    templateType: SupportingFiles
  index.mustache:
    destinationFilename: {{src}}/index.ts
    templateType: SupportingFiles
  interceptors.mustache:
    destinationFilename: {{src}}/__interceptors.ts
    templateType: SupportingFiles
