---
  nav:
    - Overview: index.md
    - Core modules: index.md#core-modules
    - Prerequisites: index.md#prerequisites
    - Code of conduct: index.md#code-of-conduct
    - License: index.md#license
