files:
  hooks.mustache:
    destinationFilename: {{src}}/hooks/hooks.tsx
    templateType: SupportingFiles
  provider.mustache:
    destinationFilename: {{src}}/hooks/provider.tsx
    templateType: SupportingFiles
  index.mustache:
    destinationFilename: {{src}}/index.ts
    templateType: SupportingFiles
