---
  nav:
    - Getting started: index.md
    - Prerequisites: prerequisites.md
    - Overview of core modules: core_modules.md
    - Project structure: project_structure.md
    - Creating a new construct: create_new_construct.md