---
  nav:
    - Getting started: index.md
    - Overview of core modules: core_modules.md
    - Project structure: project_structure.md
    - Creating a new construct: create_new_construct.md
    - How to contribute: how_to_contribute.md
    - Reporting bugs and feature requests: report_bugs_new_features.md