---
nav:
  - 'aws_arch': aws-arch
  - 'cdk_graph': cdk-graph
  - 'cdk_graph_plugin_diagram': cdk-graph-plugin-diagram
  - 'cloudscape_react_ts_website': cloudscape-react-ts-website
  - 'identity': identity
  - 'nx_monorepo': nx-monorepo
  - 'open_api_gateway': open-api-gateway
  - 'pdk_nag': pdk-nag
  - 'pipeline': pipeline
  - 'static_website': static-website
  - 'type_safe_api': type-safe-api