---
nav:
  - 'aws-arch': aws-arch
  - 'cdk-graph': cdk-graph
  - 'cdk-graph-plugin-diagram': cdk-graph-plugin-diagram
  - 'cdk-graph-plugin-threat-composer': cdk-graph-plugin-threat-composer
  - 'cloudscape-react-ts-website': cloudscape-react-ts-website
  - 'identity': identity
  - 'infrastructure': infrastructure
  - 'monorepo': monorepo
  - 'pdk-nag': pdk-nag
  - 'pipeline': pipeline
  - 'static-website': static-website
  - 'type-safe-api': type-safe-api