/*! Copyright [Amazon.com](http://amazon.com/), Inc. or its affiliates. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0 */
/**
 * Supported languages for runtimes and infrastructure
 */
export enum Language {
  TYPESCRIPT = "typescript",
  PYTHON = "python",
  JAVA = "java",
}

/**
 * Versions of node
 */
export enum NodeVersion {
  NODE_18 = "NODE_18",
  NODE_20 = "NODE_20",
}

/**
 * Versions of java
 */
export enum JavaVersion {
  JAVA_8 = "JAVA_8",
  JAVA_11 = "JAVA_11",
  JAVA_17 = "JAVA_17",
  JAVA_21 = "JAVA_21",
}

/**
 * Versions of python
 */
export enum PythonVersion {
  PYTHON_3_11 = "PYTHON_3_11",
  PYTHON_3_12 = "PYTHON_3_12",
}

/**
 * Supported libraries for code generation
 */
export enum Library {
  TYPESCRIPT_REACT_QUERY_HOOKS = "typescript-react-query-hooks",
}

export enum WebSocketLibrary {
  TYPESCRIPT_WEBSOCKET_CLIENT = "typescript-websocket-client",
  TYPESCRIPT_WEBSOCKET_HOOKS = "typescript-websocket-hooks",
}

/**
 * Formats for documentation generation
 */
export enum DocumentationFormat {
  /**
   * HTML Documentation generated by redoc
   * @see https://github.com/Redocly/redoc
   */
  HTML_REDOC = "html_redoc",
  /**
   * OpenAPI Generator 'html2' documentation
   * @see https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/html2.md
   */
  HTML2 = "html2",
  /**
   * OpenAPI Generator 'markdown' documentation
   * @see https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/markdown.md
   */
  MARKDOWN = "markdown",
  /**
   * OpenAPI Generator 'plantuml' documentation
   * @see https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/plantuml.md
   */
  PLANTUML = "plantuml",
}
