files:
  operationConfig.mustache:
    destinationFilename: {{src}}/api/operation_config.py
    templateType: SupportingFiles
  response.mustache:
    destinationFilename: {{src}}/response.py
    templateType: SupportingFiles
  interceptors.mustache:
    destinationFilename: {{src}}/__interceptors.py
    templateType: SupportingFiles
