---
nav:
  - user_guides/index.md
  - "Using Smithy": user_guides/using_smithy.md
  - "Using OpenAPI": user_guides/using_openapi.md
  - "Integrations": user_guides/integrations.md
  - "Authorizers": user_guides/authorizers.md
  - "Lambda Handlers": user_guides/lambda_handlers.md
  - "React Query Hooks": user_guides/typescript_react_query_hooks.md
  - "API Keys": user_guides/api_keys.md
  - "Custom Integration Example: ECS and NLB": user_guides/custom_integration_ecs.md