name: build
on:
  pull_request: {}
  workflow_dispatch: {}
env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      self_mutation_happened: ${{ steps.self_mutation.outputs.self_mutation_happened }}
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Synth Project
        run: pnpm projen
      - name: Build
        run: pnpm build
      - name: Check for mutations
        run: git diff --ignore-space-at-eol --exit-code
